- pmpro-pay-by-check.php
FIX: "Table not found" error when processing recurring check payments
> FIX: "Table not found" error

- pmpro-pay-by-check.php
Bug Fix/Enhancement: Only support 'check' orders while in grace period and ignore other payment gateways.
Fixes an issue for existing user's having previous orders with other gateways besides 'check'. Resolves issues with MMPU.
> Only query check orders.

- pmpro-pay-by-check.php
There was a lingering table usage on the block added to membership checkout for this Add On. We have migrated to a format as that used in the Add PayPal Express Add On - this update improves the code in the Pay By Check Add On to match that standard.
> Removing the table and formatting frontend as we do in Add PayPal Express or Core PayPal gateway

- pmpro-pay-by-check.php
Resolves #73
Steps to reproduce the behavior:
1. Activate Pay by Check
2. Install MMPU
3. Add the following to a page:
```
[membership]
Our association is run by its members, please help to run the site by volunteering.
[/membership]
[membership level="0"]
You need to be a member to volunteer.
[/membership]
```
See error on page:
```
( ! ) Warning: foreach() argument must be of type array|object, bool given in /Users/xxyy/Local Sites/test/app/public/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php on line 491
```
> Fixes a PHP error

- pmpro-pay-by-check.php
Only check a user's levels for content access if they are logged in.
Resolves https://github.com/strangerstudios/pmpro-pay-by-check/issues/71
1. Go to Pages > Add New and create a new page containing the shortcode `[membership level="0"]Display for non-members [/membership]` and publish the page.
2. In a new private/incognito browser navigate to this page as a non-logged-in visitor
3. Confirm that _Display for non-members_ is displayed on this page.
> Set level access check for logged in users only

- pmpro-pay-by-check.php
This PR fixes a PHP 8 fatal error thrown in the `pmpropbc_reminder_emails` function when a WP user referenced in an order no longer exists.
From the [PHP 8 migration guide](https://www.php.net/manual/en/migration80.incompatible.php):
>A number of warnings have been converted into [Error](https://www.php.net/manual/en/class.error.php) exceptions:
> - Attempting to write to a property of a non-object. Previously this implicitly created an stdClass object for null, false and empty strings.
The fixed error:
```
PHP Fatal error:  Uncaught Error: Attempt to assign property "membership_level" on bool in /home/MY_SITE/public_html/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php:817
Stack trace:
#0 /home/MY_SITE/public_html/wp-includes/class-wp-hook.php(307): pmpropbc_reminder_emails() …
```
> Fix PHP 8 fatal errors in `pmpropbc_reminder_emails`.

- pmpro-pay-by-check.php
Support Auto-Renewal Checkbox for reminder emails and cancel overdue orders. This may also help with other cases of prematurely expiring.
Resolves https://github.com/strangerstudios/pmpro-pay-by-check/issues/69
> Support Auto-Renewal Checkbox

- pmpro-pay-by-check.php
* ENHANCEMENT: Added in a custom confirmation page when order is pending with check. Translatable.
Resolves: https://github.com/strangerstudios/pmpro-pay-by-check/issues/76
> Overwrite the confirmation mesasge when PBC is used.

- pmpro-pay-by-check.php
Issue:
1. Using shortcode `[membership level="0"]`
2. Logged in user without a membership level tries to view the content and should be able to
3. `is_user_logged_in()` will be `true`
4. `pmprobpc_memberHasAccessWithAnyLevel( $current_user->ID )` will set `$hasaccess` to false since the user does not have a membership level
This behavior is incorrect. If we are trying to show content to non-members, then we absolutely don't want to hide the content because this logged-in non-member don't have a level.
> Fix membership shortcode for non-member users

- pmpro-pay-by-check.php
The PayPal Express Add On adds a toggle section which doesn't get removed for levels that only allow a Check payment. 
This removes that section where necessary.
1. Activate PMPro, PayPal Express Add On and Pay By Check Add On
2. Set a level to only allow payment by Check
3. The toggle/radio buttons should no longer show on checkout
Check only levels no longer show multiple gateway options
> Removes the PPExp Toggle Section for a Check Only level

- pmpro-pay-by-check.php
Should only be merged once this PR is confirmed to be merged into the PMPro v3.0 branch: https://github.com/strangerstudios/paid-memberships-pro/pull/2506
This PR specifically stops pulling the checkout level from the `$_REQUEST` variable (since we are prefixing the `level` parameter in 3.0) and instead uses the `pmpro_getLevelAtCheckout()` function.
> No longer pulling level from $_REQUEST

- pmpro-pay-by-check.php
PMPro v2.11 updated the checkout page headings hierarchy from h3 to h2. This PR updates this Add On to follow the same pattern for accessibility.
> Updating headings hierarchy to match new PMPro checkout page for a11y

- pmpro-pay-by-check.php
> No longer sending duplicate invoice emails

- pmpro-pay-by-check.php
Noting the date that an order is cancelled (as the query above expects that data to be there) and now setting the order status to "Error" to discourage admins from later trying to switch it to success, even though the user has already lost their membership.
> Setting order status to error on failed payment

- js/pmpro-pay-by-check.js
- pmpro-pay-by-check.php
In the last update, we began using the `pmpro_getLevelAtCheckout()` function to avoid pulling level IDs directly from the `$_REQUEST` variable. This came with some performance issues where some sites were running out of PHP memory. Looking at the backtrace for a site, the issue originated from the `pmpropbc_pmpro_get_gateway()` function.
The first thought here was to try to make that function more efficient by using caching or limiting when it runs, but taking a step back, that plugin seems unnecessary altogether. The `pmpropbc_pmpro_get_gateway()` function only actually ever has an effect if the level being purchased is a "pay by check only" level. Levels that can be purchased via check or another gateway do not use this code and work correctly. So the `pmpropbc_pmpro_get_gateway()` …
> Improving performance by no longer filtering gateway option

- pmpro-pay-by-check.php
If a user is logged out, `pmpro_getMembershipLevelsForUser()` will return `false`. We need to account for that possibility in our code.
> Avoiding PHP warnings when user logged out

- pmpro-pay-by-check.php
Marks the address field as not required, even though they've been hidden already
1. Set up a level with the PBC Add On and set a level to only be able to checkout with a check
2. Activate the Address for Free Levels Add On
3. Run a test checkout
> Adds support when using PBC with Address for Free Levels

- pmpro-pay-by-check.php
- Fixing issue where new order would not carry over time from previous order
- Removing unused query
- Fixing `timestamp` variable in query to be a datetime like SQL expects
> Fixing order timestamp, removing dupe/wrong query

- pmpro-pay-by-check.php
Fixing issue where each $combo is being applied to each user's membership regardless of the actual cycle period/cycle number set for that membership, meaning that users may have orders created when they should not be.
Resolves #60 
> Fixing $combo issues

- pmpro-pay-by-check.php
Fixes a PHP error that is caused by the [membership] shortcode not having a levels attribute
1. Add the `[membership]` shortcode to a page
2. Sign up for a level with a check payment
3. Visit the page - No error should show. Previously: `Warning: foreach() argument must be of type array|object, bool given in /Users/jarrydlong/Local Sites/paid-memberships-pro/app/public/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php on line 634`
> Fixes an error caused by no attr in membership shortcode

- pmpro-pay-by-check.php
Adjust the SQL query to it's original state, in a similar manner but minor refactor.
> Dupe query

- pmpro-pay-by-check.php
* Just add, add the templates to the templates area
catch templates filter and add Add On templates to the template array.
Resolves #62 .
> Add Pay-by-Check email templates to Templates Area

- pmpro-pay-by-check.php
* Replace Add occurrences with payment gateway if exists
Resolves XXX.
1.
2.
3.
> PBC Labeling

- pmpro-pay-by-check.php
Fixed issue in PMPro v3.0+ where recurring orders could be created for old Check orders even if the last payment was from a different payment gateway.
This means that if a user paid by check and then switched to paying with Stripe, recurring check orders could still be created in `pending` status and, if not marked as `success`, the user's membership could be canceled.
The change in PMPro v3.0 that brought about this issue was the removal of the `cancelled` status. The query fix by this PR only looks for orders in `pending` or `success` status to create a recurring order for, and since orders for old memberships were in `cancelled` status previously, recurring orders would not be created for them. Now that all `cancelled` orders are now `success`, this safeguard no longer works.
The fix …
> Do not create recurring orders if last payment was from another gateway

- includes/crons.php
Avoids sending a membership cancellation email in cases where a user submitted a checkout but their first payment was never received.
> Only sending the cancellation email if a level was removed

- includes/checkout.php
The check instructions were missed in our first pass here. This updates the instructions to also use the design as in core's check gateway.
How it looks with previous versions of PMPro
How it looks with v3.1+ of PMPro
> Small update to show check instructions in a box for v3.1+

- includes/checkout.php
If the user has a membership level and purchases it again with a subscription, the new subscription will be immediately canceled. This is happening because:
1. The order was being saved in `success` status before the level changed occurred
2. This caused the PMPro_Subscription entry to be added before level change
3. During level change, all existing subscriptions for cancelled levels are deleted
The fix: Initiate the level change before the order is saved in "success" status
> Fix subscriptions being immediately cancelled

- includes/checkout.php
If we call `pmpro_getLevelAtCheckout()`, the incorrect value may be cached for that function. This will cause issues with PayPal Express in PMPro v3.2.
Resolves XXX.
> Delay calling pmpro_getLevelAtCheckout() until the checkout level is retrieved

- includes/crons.php
Likely since the MemberOrder cleanup work in PMPro v2.2, recurring orders created by PBC are being created with a $0 total. This fixes that issue by directly setting the total and subtotal when creating recurring orders instead of relying on the `InitialPayment` and `PaymentAmount` dynamic properties.
> Setting the order total directly on recurring payments

- includes/checkout.php
Resolves #132 
Steps to reproduce the behavior:
Have Stripe (Checkout), the PayPal Express Add On and the Pay by Check Add On active
My level had an initial amount, expiration date, and the 'Allow Paying by Check' setting set to 'Users can only pay by check'
Checkout with this level
You'll automatically be redirected to Stripe Checkout
> Make sure that the order gateway is check if the level is check only

- includes/crons.php
Hook into pmpro_registered_crons to add PBC crons to site health info
Resolves #124 .
Pull site health info and observe that crons are there
>  * Hook into pmpro_registered_crons to add PBC crons to site health info

- includes/crons.php
Resolves #136 
1. Use the `pmpro_tax` filter to apply a tax on checkout e.g. https://gist.github.com/dwanjuki/c9ceaa536d5662e58d1a6a0da6736332
2. Complete checkout for a recurring membership.
3. Check recurring orders for the subscription.
4. Observe that tax is included on both the initial order and recurring orders, if the conditions for the tax are met.
> Fixed an issue where tax would not be included on recurring check orders.
> Including tax amount on recurring orders

- classes/email-templates/class-pmpro-email-template-check-pending-admin.php
* BUG FIX: Fixed an issue for !!name!! and !!display_name!! variables showing the admins name, and not the members name for admin emails. See lines 145-146,
* REFACTOR: Adjusted the `@since` docblocks as it was incorrectly versioned and applied minor WPCS (fix spacing issues)
Resolves #145 .
1. Configure a membership level and complete a checkout using the Pay by Check gateway.
2. Observe the Payment by Check – Pending (send to admin) email received by the admin.
3. Notice that the !!name!! and !!display_name!! placeholder shows the admin’s name, not the member’s.
4. Retest the above steps after merging this PR to see that either variable now shows the member's name.
> Fixed issue with email template variable
